INSERT INTO params (name, category, subcategory, unit_default, sort_order) VALUES
('Umumiy ishlab chiqarish plani soni',                   'Ishlab chiqarish','Umumiy',      'dona',  1),
('Trelloda umumiy zakaz soni',                            'Ishlab chiqarish','Umumiy',      'dona',  2),
('PU zakaz soni',                                         'Ishlab chiqarish','Umumiy',      'dona',  3),
('Pu bo''lim plan bajarilish ko''rsatkichi',              'Ishlab chiqarish','PU bo''lim',  '%',    10),
('PU ishlab chiqarilgan mahsulot soni',                   'Ishlab chiqarish','PU bo''lim',  'dona', 11),
('Pu bo''lim hodimlar soni',                              'Ishlab chiqarish','PU bo''lim',  'kishi',12),
('PU bo''lim hodim samaradorligi',                        'Ishlab chiqarish','PU bo''lim',  '%',    13),
('PU jami ish vaqti',                                     'Ishlab chiqarish','PU bo''lim',  'soat', 14),
('PU bo''lim ish vaqti',                                  'Ishlab chiqarish','PU bo''lim',  'soat', 15),
('PU bo''lim ishlab chiqarish tezligi',                   'Ishlab chiqarish','PU bo''lim',  'dona', 16),
('PU bo''lim to''xtalishlar vaqti (soat hisobida)',       'Ishlab chiqarish','PU bo''lim',  'soat', 17),
('PU ishlatilgan xomashyo miqdori',                       'Ishlab chiqarish','PU bo''lim',  'kg',   18),
('PU atxo''t miqdori',                                    'Ishlab chiqarish','PU bo''lim',  'kg',   19),
('PU xomashyo qoldiq miqdori',                            'Ishlab chiqarish','PU bo''lim',  'kg',   20),
('Pu ikkilamchi xomashyo miqdori',                        'Ishlab chiqarish','PU bo''lim',  'kg',   21),
('TEP zakaz soni',                                        'Ishlab chiqarish','TEP bo''lim', 'dona', 30),
('TEP bo''lim plan bajarilish ko''rsatkichi',             'Ishlab chiqarish','TEP bo''lim', '%',    31),
('TEP ishlab chiqarilgan mahsulot soni',                  'Ishlab chiqarish','TEP bo''lim', 'dona', 32),
('TEP bo''lim hodimlar soni',                             'Ishlab chiqarish','TEP bo''lim', 'kishi',33),
('TEP bo''lim hodim samaradorligi',                       'Ishlab chiqarish','TEP bo''lim', '%',    34),
('TEP jami ish vaqti',                                    'Ishlab chiqarish','TEP bo''lim', 'soat', 35),
('TEP bo''lim ish vaqti',                                 'Ishlab chiqarish','TEP bo''lim', 'soat', 36),
('TEP bo''lim ishlab chiqarish tezligi (soat hisobida)', 'Ishlab chiqarish','TEP bo''lim', 'soat', 37),
('TEP bo''lim to''xtalishlar vaqti',                      'Ishlab chiqarish','TEP bo''lim', 'soat', 38),
('TEP ishlatilgan xomashyo miqdori',                      'Ishlab chiqarish','TEP bo''lim', 'kg',   39),
('TEP atxo''t miqdori',                                   'Ishlab chiqarish','TEP bo''lim', 'kg',   40),
('TEP xomashyo qoldiq miqdori',                           'Ishlab chiqarish','TEP bo''lim', 'kg',   41)
ON CONFLICT (name) DO NOTHING;
